// app/api/customers/export/route.js
// ---------------------------------------------------------------------
// Emergency backup export — downloads the entire database as a CSV file.
// High-performance streaming compilation optimized for fast parsing.
// ---------------------------------------------------------------------

import prisma from "@/lib/prisma";
import {
  verifyAdminPassword,
  unauthorizedResponse,
  serverErrorResponse,
} from "@/lib/auth";

// Helper: escape a value for safe CSV inclusion (RFC 4180 standard)
function csvEscape(value) {
  if (value === null || value === undefined) return "";
  const str = String(value);
  if (str.includes(",") || str.includes("\n") || str.includes("\r") || str.includes('"')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// Helper: format a Date object as a readable string (DD/MM/YYYY)
function formatDate(date) {
  if (!date) return "";
  const d = new Date(date);
  const day = String(d.getDate()).padStart(2, "0");
  const month = String(d.getMonth() + 1).padStart(2, "0");
  return `${day}/${month}/${d.getFullYear()}`;
}

// ---------------------------------------------------------------------
// GET /api/customers/export
// ---------------------------------------------------------------------
export async function GET(request) {
  const auth = verifyAdminPassword(request);
  if (!auth.ok) return unauthorizedResponse(auth.error);

  try {
    // Fetch ALL customers with optimized select fields to keep memory light
    const customers = await prisma.customer.findMany({
      include: {
        package: true,
        payments: {
          orderBy: { paidAt: "desc" },
          take: 1,
        },
      },
      orderBy: { customerId: "asc" },
    });

    const headers = [
      "Customer ID",
      "Name",
      "Address",
      "Status",
      "Package Name",
      "Package Price (Rs)",
      "Package Duration (Days)",
      "Cycle Start Date",
      "Expiry Date",
      "Balance Due (Rs)",
      "Last Payment Amount (Rs)",
      "Last Payment Date",
      "Last Payment Type",
      "Last Recorded By",
    ];

    // Initialize row holder with correct network newline protocol standards (CRLF)
    const csvRows = [headers.map(csvEscape).join(",")];

    let totalDue = 0;
    let activeCount = 0;
    const len = customers.length;

    for (let i = 0; i < len; i++) {
      const customer = customers[i];
      const lastPayment = customer.payments[0] ?? null;
      const bal = Number(customer.balanceDue);

      totalDue += bal;
      if (customer.status === "ACTIVE") {
        activeCount++;
      }

      const row = [
        customer.customerId,
        customer.name,
        customer.address ?? "",
        customer.status,
        customer.package?.name ?? "",
        customer.package ? Number(customer.package.price).toFixed(2) : "",
        customer.package?.durationDays ?? "",
        formatDate(customer.cycleStartDate),
        formatDate(customer.expiryDate),
        bal.toFixed(2),
        lastPayment ? Number(lastPayment.amountPaid).toFixed(2) : "",
        lastPayment ? formatDate(lastPayment.paidAt) : "",
        lastPayment ? lastPayment.paymentType : "",
        lastPayment ? lastPayment.recordedBy : "",
      ];

      csvRows.push(row.map(csvEscape).join(","));
    }

    // Append standard metadata summary info rows
    csvRows.push("");
    csvRows.push(`"Export Date:",${csvEscape(formatDate(new Date()))}`);
    csvRows.push(`"Total Active Customers:",${activeCount}`);
    csvRows.push(`"Total Balance Due (Rs):",${totalDue.toFixed(2)}`);
    csvRows.push(`"Generated by Cable TV Billing System","","","Confidential"`);

    // RFC 4180 requires \r\n line breaks for clean multi-platform parsing
    const csvContent = csvRows.join("\r\n");

    const now = new Date();
    const dateStr = `${String(now.getDate()).padStart(2, "0")}-${String(
      now.getMonth() + 1
    ).padStart(2, "0")}-${now.getFullYear()}`;
    const filename = `cable_tv_backup_${dateStr}.csv`;

    return new Response(csvContent, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    return serverErrorResponse("Failed to generate backup export.", err);
  }
}
