// app/api/customers/export/route.js
// ---------------------------------------------------------------------
// Emergency backup export — downloads the entire database as a CSV file.
//
// GET /api/customers/export  — Admin only.
//                              Returns a downloadable CSV containing:
//                              - All customers (active + inactive)
//                              - Their current package details
//                              - Current balance due
//                              - Billing cycle dates
//                              - Last payment info
//
// This is your father's safety net. One tap downloads everything to
// his phone/device instantly. The CSV can be re-imported later or
// opened in Excel/Google Sheets for manual review.
// ---------------------------------------------------------------------

import prisma from "@/lib/prisma";
import {
  verifyAdminPassword,
  unauthorizedResponse,
  serverErrorResponse,
} from "@/lib/auth";

// Helper: escape a value for safe CSV inclusion.
// Wraps in quotes and escapes any internal quotes.
function csvEscape(value) {
  if (value === null || value === undefined) return "";
  const str = String(value);
  // If the value contains a comma, newline, or quote — wrap in quotes
  if (str.includes(",") || str.includes("\n") || str.includes('"')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// Helper: format a Date object as a readable string (DD/MM/YYYY)
function formatDate(date) {
  if (!date) return "";
  const d = new Date(date);
  const day = String(d.getDate()).padStart(2, "0");
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
}

// ---------------------------------------------------------------------
// GET /api/customers/export
// ---------------------------------------------------------------------
export async function GET(request) {
  const auth = verifyAdminPassword(request);
  if (!auth.ok) return unauthorizedResponse(auth.error);

  try {
    // Fetch ALL customers regardless of status, with their package
    // and their most recent payment record.
    const customers = await prisma.customer.findMany({
      include: {
        package: true,
        payments: {
          orderBy: { paidAt: "desc" },
          take: 1, // only the most recent payment
        },
      },
      orderBy: { customerId: "asc" },
    });

    // ------------------------------------------------------------------
    // Build CSV content
    // ------------------------------------------------------------------
    const headers = [
      "Customer ID",
      "Name",
      "Address",
      "Status",
      "Package Name",
      "Package Price (Rs)",
      "Package Duration (Days)",
      "Cycle Start Date",
      "Expiry Date",
      "Balance Due (Rs)",
      "Last Payment Amount (Rs)",
      "Last Payment Date",
      "Last Payment Type",
      "Last Recorded By",
    ];

    const csvRows = [headers.map(csvEscape).join(",")];

    for (const customer of customers) {
      const lastPayment = customer.payments[0] ?? null;

      const row = [
        customer.customerId,
        customer.name,
        customer.address ?? "",
        customer.status,
        customer.package?.name ?? "",
        customer.package ? Number(customer.package.price).toFixed(2) : "",
        customer.package?.durationDays ?? "",
        formatDate(customer.cycleStartDate),
        formatDate(customer.expiryDate),
        Number(customer.balanceDue).toFixed(2),
        lastPayment ? Number(lastPayment.amountPaid).toFixed(2) : "",
        lastPayment ? formatDate(lastPayment.paidAt) : "",
        lastPayment ? lastPayment.paymentType : "",
        lastPayment ? lastPayment.recordedBy : "",
      ];

      csvRows.push(row.map(csvEscape).join(","));
    }

    // Add a summary footer
    const totalDue = customers.reduce(
      (sum, c) => sum + Number(c.balanceDue),
      0
    );
    const activeCount = customers.filter((c) => c.status === "ACTIVE").length;

    csvRows.push(""); // blank line before footer
    csvRows.push(`"Export Date:",${csvEscape(formatDate(new Date()))}`);
    csvRows.push(`"Total Customers:",${activeCount}`);
    csvRows.push(`"Total Balance Due (Rs):",${totalDue.toFixed(2)}`);
    csvRows.push(`"Generated by Cable TV Billing System","","","Confidential"`);

    const csvContent = csvRows.join("\n");

    // ------------------------------------------------------------------
    // Build filename with today's date: backup_DD-MM-YYYY.csv
    // ------------------------------------------------------------------
    const now = new Date();
    const dateStr = `${String(now.getDate()).padStart(2, "0")}-${String(
      now.getMonth() + 1
    ).padStart(2, "0")}-${now.getFullYear()}`;
    const filename = `cable_tv_backup_${dateStr}.csv`;

    // ------------------------------------------------------------------
    // Return as a file download response
    // The Content-Disposition header triggers "Save file" on the browser.
    // ------------------------------------------------------------------
    return new Response(csvContent, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    return serverErrorResponse("Failed to generate backup export.", err);
  }
}
